# fly.toml app configuration file for idp-srv
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "idp-srv"
primary_region = "sjc"

[build]
  dockerfile = "./idp.fly.dockerfile"

[env]
  IDP_PORT = "4000"
  IDP_ISSUER = "http://localhost:4000"
  COOKIE_SECRET = "dev-idp-cookie-secret"
  CLIENT_IN_RESOURCE = "wiki0-at-todo0"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
